@startuml

[*] --> STATE_UNKNOWN

STATE_UNKNOWN --> STATE_ROOT : IXFEvent::Initial

STATE_ROOT --> STATE_POSITION_CHANGED : IXFEvent::Event && id = POSITION_CHANGED_EVENT
STATE_POSITION_CHANGED --> STATE_ROOT : Null

@enduml
